MIMIC:
  images_path_train: "/raid/s2198939/MIMIC_Dataset/physionet.org/files/mimic-cxr-jpg/2.0.0"
  images_path_val: "/raid/s2198939/MIMIC_Dataset/physionet.org/files/mimic-cxr-jpg/2.0.0"
  train_csv: "/raid/s2198939/MIMIC_Dataset/physionet.org/files/mimic-cxr-jpg/2.0.0/Prepared_CSVs/FINAL_TRAIN.xlsx"
  val_csv: "/raid/s2198939/MIMIC_Dataset/physionet.org/files/mimic-cxr-jpg/2.0.0/Prepared_CSVs/FINAL_VAL.xlsx"
  test_csv: "/raid/s2198939/MIMIC_Dataset/physionet.org/files/mimic-cxr-jpg/2.0.0/Prepared_CSVs/FINAL_TEST.xlsx"
  counts_csv: "/raid/s2198939/MIMIC_Dataset/physionet.org/files/mimic-cxr-jpg/2.0.0/Prepared_CSVs/MIMIC_Prompts_count_df.csv"
  # memorization_csv: "/raid/s2198939/MIMIC_Dataset/physionet.org/files/mimic-cxr-jpg/2.0.0/Prepared_CSVs/MEMORIZED_PROMPTS.xlsx"
  memorization_csv: "/raid/s2198939/MIMIC_Dataset/physionet.org/files/mimic-cxr-jpg/2.0.0/Prepared_CSVs/PROMPTS_WITH_MAX_TOKENS.xlsx"
imagenette:
  images_path_train: "/raid/s2198939/"
  images_path_val: "/raid/s2198939/"
  train_csv: "/raid/s2198939/imagenette2-320/train.csv"
  val_csv: "/raid/s2198939/imagenette2-320/val.csv"


